spring:
  application:
    name: springboot-demo
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  metrics:
    tags:
      application: ${spring.application.name}
