spring:
  application:
    name: springboot-demo
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
##    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${PID} [%thread] %-5level %logger{50} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID} %X{traceId} --- %thread %F:%L %logger{50} : %msg##%n"

